### ISSUE TITLE
 stopTiming called async for world - chunkLoad - TileEntities

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch-1.8#3]
```
[14:06:35] [Craft Scheduler Thread - 15/ERROR]: stopTiming called async for MinaRecheada - chunkLoad - TileTicks
[14:06:35] [Craft Scheduler Thread - 15/WARN]: java.lang.Throwable
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:18)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:144)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:126)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getOrCreateChunkFast(ChunkProviderServer.java:122)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getOrCreateChunk(ChunkProviderServer.java:225)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:144)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:179)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:187)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:183)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.util.BlockIterator.scan(BlockIterator.java:352)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.util.BlockIterator.hasNext(BlockIterator.java:286)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:136)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:191)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at me.mrpowergamerbr.sparklycore.utils.BossbarAPI$1.run(BossbarAPI.java:126)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:06:35] [Craft Scheduler Thread - 15/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MrPowerGamerBR** [comment]
Whoops, already found the issue, sorry.
