### ISSUE TITLE
Error executing task ... java.lang.NullPointerException (Related to Enchantment Tables?)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch-1.8#5]
```
[21:15:21] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.MinecraftServer.processNetworkQueue(MinecraftServer.java:117) [torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:795) [torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:381) [torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:730) [torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:633) [torch.jar:git-Torch-3135173]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.ContainerEnchantTable.a(ContainerEnchantTable.java:111) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.ContainerEnchantTable$1.update(ContainerEnchantTable.java:27) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.InventorySubcontainer.setItem(InventorySubcontainer.java:152) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.Slot.set(Slot.java:55) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.ContainerEnchantTable.b(ContainerEnchantTable.java:342) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.Container.clickItem(Container.java:253) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1697) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[torch.jar:git-Torch-3135173]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:10) ~[torch.jar:git-Torch-3135173]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[torch.jar:git-Torch-3135173]
	... 6 more
```

**Comment by MrPowerGamerBR** [comment]
This was already "fixed", this is a dupe bug if you open a Enchant Table where it doesn't exist one (with the Bukkit API).

This also happens in Spigot and any of the Spigot forks.
